name: '🧪 Build Testing Plugin'

on:
  push:
    branches:
      - testing
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '9.0.x'

      - name: Build and Package Plugin
        id: package
        uses: oddstr13/jellyfin-plugin-repository-manager@v1.1.1
        with:
          dotnet-target: net9.0
          version: 13.1.0.${{ github.run_number }}

      - name: Upload Plugin Package
        uses: actions/upload-artifact@v7
        with:
          name: tvmaze-test-${{ github.run_number }}
          path: ${{ steps.package.outputs.artifact }}
          retention-days: 30
          if-no-files-found: error
